# /* wallust template - colors-hyprland */ 

$background = rgb(000002)
$foreground = rgb(DDE8EA)
$color0 = rgb(000002)
$color1 = rgb(313237)
$color2 = rgb(313237)
$color3 = rgb(313237)
$color4 = rgb(545957)
$color5 = rgb(545957)
$color6 = rgb(768D92)
$color7 = rgb(C6D5D9)
$color8 = rgb(8A9598)
$color9 = rgb(424349)
$color10 = rgb(424349)
$color11 = rgb(424349)
$color12 = rgb(707774)
$color13 = rgb(707774)
$color14 = rgb(9DBCC3)
$color15 = rgb(C6D5D9)
